import type { ResumeTemplate } from '../types/index.js';

export type { ResumeTemplate };

export const templates: ResumeTemplate[] = [
  {
    id: 'modern-blue',
    name: '现代蓝',
    description: '简洁现代的蓝色主题，适合科技行业',
    color: '#2563EB',
    accent: '#DBEAFE',
    preview: 'linear-gradient(135deg, #2563EB 0%, #3B82F6 100%)',
  },
  {
    id: 'elegant-dark',
    name: '优雅深色',
    description: '高端大气的深色主题，适合金融咨询',
    color: '#1E293B',
    accent: '#F8FAFC',
    preview: 'linear-gradient(135deg, #1E293B 0%, #334155 100%)',
  },
  {
    id: 'creative-coral',
    name: '创意珊瑚',
    description: '温暖活力的珊瑚色，适合创意设计',
    color: '#F97316',
    accent: '#FFF7ED',
    preview: 'linear-gradient(135deg, #F97316 0%, #FB923C 100%)',
  },
  {
    id: 'minimal-sage',
    name: '极简青绿',
    description: '清新自然的青绿色，适合环保教育',
    color: '#059669',
    accent: '#ECFDF5',
    preview: 'linear-gradient(135deg, #059669 0%, #34D399 100%)',
  },
  {
    id: 'professional-violet',
    name: '专业紫',
    description: '稳重专业的紫色，适合法律医疗',
    color: '#7C3AED',
    accent: '#F5F3FF',
    preview: 'linear-gradient(135deg, #7C3AED 0%, #A78BFA 100%)',
  },
  {
    id: 'warm-rose',
    name: '温馨粉',
    description: '柔和温馨的粉色，适合人文社科',
    color: '#EC4899',
    accent: '#FDF2F8',
    preview: 'linear-gradient(135deg, #EC4899 0%, #F472B6 100%)',
  },
];

// 为每个模板创建 LeaferJS 内容
export function createTemplateContent(template: ResumeTemplate) {
  const c = template.color;
  const a = template.accent;

  return [

    // 左侧边栏背景（锁定：不可选中/拖动，解锁后可编辑）
    {
      tag: 'Rect',
      id: 'bg-left',
      x: 0,
      y: 0,
      width: 240,
      height: 700,
      fill: c,
      cornerRadius: 0,
      editable: false,
      hittable: false,
      draggable: false,
    },
    // 头像区域
    {
      tag: 'Ellipse',
      x: 70,
      y: 30,
      width: 100,
      height: 100,
      fill: 'rgba(255,255,255,0.2)',
      editable: true,
    },
    // 姓名
    {
      tag: 'Text',
      x: 30,
      y: 150,
      width: 180,
      text: '张三',
      fill: '#FFFFFF',
      fontSize: 28,
      fontWeight: 'bold',
      fontFamily: 'Poppins, sans-serif',
      textAlign: 'center',
      editable: true,
    },
    // 职位
    {
      tag: 'Text',
      x: 30,
      y: 185,
      width: 180,
      text: '高级产品设计师',
      fill: 'rgba(255,255,255,0.8)',
      fontSize: 13,
      fontFamily: 'Inter, sans-serif',
      textAlign: 'center',
      editable: true,
    },
    // 联系信息标题
    {
      tag: 'Text',
      x: 30,
      y: 240,
      text: '联系方式',
      fill: '#FFFFFF',
      fontSize: 14,
      fontWeight: '600',
      fontFamily: 'Inter, sans-serif',
      editable: true,
    },
    // 联系信息分隔线
    {
      tag: 'Rect',
      x: 30,
      y: 262,
      width: 40,
      height: 3,
      fill: 'rgba(255,255,255,0.5)',
      cornerRadius: 1.5,
      editable: true,
    },
    // 邮箱
    {
      tag: 'Text',
      x: 30,
      y: 280,
      text: 'zhangsan@email.com',
      fill: 'rgba(255,255,255,0.7)',
      fontSize: 11,
      fontFamily: 'Inter, sans-serif',
      editable: true,
    },
    // 电话
    {
      tag: 'Text',
      x: 30,
      y: 300,
      text: '138-0000-0000',
      fill: 'rgba(255,255,255,0.7)',
      fontSize: 11,
      fontFamily: 'Inter, sans-serif',
      editable: true,
    },
    // 地址
    {
      tag: 'Text',
      x: 30,
      y: 320,
      text: '北京市朝阳区',
      fill: 'rgba(255,255,255,0.7)',
      fontSize: 11,
      fontFamily: 'Inter, sans-serif',
      editable: true,
    },
    // 技能标题
    {
      tag: 'Text',
      x: 30,
      y: 370,
      text: '专业技能',
      fill: '#FFFFFF',
      fontSize: 14,
      fontWeight: '600',
      fontFamily: 'Inter, sans-serif',
      editable: true,
    },
    // 技能分隔线
    {
      tag: 'Rect',
      x: 30,
      y: 392,
      width: 40,
      height: 3,
      fill: 'rgba(255,255,255,0.5)',
      cornerRadius: 1.5,
      editable: true,
    },
    // 技能条 - Figma
    {
      tag: 'Text',
      x: 30,
      y: 415,
      text: 'Figma',
      fill: 'rgba(255,255,255,0.9)',
      fontSize: 11,
      fontFamily: 'Inter, sans-serif',
      editable: true,
    },
    {
      tag: 'Rect',
      x: 30,
      y: 433,
      width: 180,
      height: 5,
      fill: 'rgba(255,255,255,0.2)',
      cornerRadius: 2.5,
      editable: true,
    },
    {
      tag: 'Rect',
      x: 30,
      y: 433,
      width: 162,
      height: 5,
      fill: '#FFFFFF',
      cornerRadius: 2.5,
      editable: true,
    },
    // 技能条 - Sketch
    {
      tag: 'Text',
      x: 30,
      y: 453,
      text: 'Sketch',
      fill: 'rgba(255,255,255,0.9)',
      fontSize: 11,
      fontFamily: 'Inter, sans-serif',
      editable: true,
    },
    {
      tag: 'Rect',
      x: 30,
      y: 471,
      width: 180,
      height: 5,
      fill: 'rgba(255,255,255,0.2)',
      cornerRadius: 2.5,
      editable: true,
    },
    {
      tag: 'Rect',
      x: 30,
      y: 471,
      width: 144,
      height: 5,
      fill: '#FFFFFF',
      cornerRadius: 2.5,
      editable: true,
    },
    // 技能条 - 原型设计
    {
      tag: 'Text',
      x: 30,
      y: 491,
      text: '原型设计',
      fill: 'rgba(255,255,255,0.9)',
      fontSize: 11,
      fontFamily: 'Inter, sans-serif',
      editable: true,
    },
    {
      tag: 'Rect',
      x: 30,
      y: 509,
      width: 180,
      height: 5,
      fill: 'rgba(255,255,255,0.2)',
      cornerRadius: 2.5,
      editable: true,
    },
    {
      tag: 'Rect',
      x: 30,
      y: 509,
      width: 153,
      height: 5,
      fill: '#FFFFFF',
      cornerRadius: 2.5,
      editable: true,
    },
    // 右侧主内容区背景（锁定：不可选中/拖动，解锁后可编辑）
    {
      tag: 'Rect',
      id: 'bg-right',
      x: 240,
      y: 0,
      width: 360,
      height: 700,
      fill: '#FFFFFF',
      cornerRadius: 0,
      editable: false,
      hittable: false,
      draggable: false,
    },
    // 个人简介标题
    {
      tag: 'Text',
      x: 270,
      y: 40,
      text: '个人简介',
      fill: c,
      fontSize: 16,
      fontWeight: '700',
      fontFamily: 'Inter, sans-serif',
      editable: true,
    },
    // 标题下划线
    {
      tag: 'Rect',
      x: 270,
      y: 64,
      width: 40,
      height: 3,
      fill: c,
      cornerRadius: 1.5,
      editable: true,
    },
    // 个人简介内容
    {
      tag: 'Text',
      x: 270,
      y: 80,
      width: 300,
      text: '拥有8年产品设计经验的资深设计师，\n专注于用户体验和视觉设计。曾在多家\n知名科技公司主导设计项目，擅长将复\n杂需求转化为简洁直观的用户界面。',
      fill: '#475569',
      fontSize: 11,
      fontFamily: 'Inter, sans-serif',
      lineHeight: 20,
      editable: true,
    },
    // 工作经历标题
    {
      tag: 'Text',
      x: 270,
      y: 180,
      text: '工作经历',
      fill: c,
      fontSize: 16,
      fontWeight: '700',
      fontFamily: 'Inter, sans-serif',
      editable: true,
    },
    {
      tag: 'Rect',
      x: 270,
      y: 204,
      width: 40,
      height: 3,
      fill: c,
      cornerRadius: 1.5,
      editable: true,
    },
    // 工作经历 1
    {
      tag: 'Ellipse',
      x: 270,
      y: 225,
      width: 10,
      height: 10,
      fill: c,
      editable: true,
    },
    {
      tag: 'Text',
      x: 290,
      y: 222,
      text: '高级产品设计师',
      fill: '#1E293B',
      fontSize: 13,
      fontWeight: '600',
      fontFamily: 'Inter, sans-serif',
      editable: true,
    },
    {
      tag: 'Text',
      x: 440,
      y: 222,
      text: '2020 - 至今',
      fill: '#94A3B8',
      fontSize: 10,
      fontFamily: 'Inter, sans-serif',
      editable: true,
    },
    {
      tag: 'Text',
      x: 290,
      y: 242,
      text: '某科技公司 · 北京',
      fill: '#94A3B8',
      fontSize: 10,
      fontFamily: 'Inter, sans-serif',
      editable: true,
    },
    {
      tag: 'Text',
      x: 290,
      y: 262,
      width: 280,
      text: '• 主导公司核心产品的UI/UX设计工作\n• 建立并维护设计系统，提升团队效率40%\n• 用户满意度提升25%，获得年度优秀员工',
      fill: '#475569',
      fontSize: 11,
      fontFamily: 'Inter, sans-serif',
      lineHeight: 20,
      editable: true,
    },
    // 工作经历 2
    {
      tag: 'Ellipse',
      x: 270,
      y: 340,
      width: 10,
      height: 10,
      fill: c,
      editable: true,
    },
    {
      tag: 'Text',
      x: 290,
      y: 337,
      text: 'UI/UX设计师',
      fill: '#1E293B',
      fontSize: 13,
      fontWeight: '600',
      fontFamily: 'Inter, sans-serif',
      editable: true,
    },
    {
      tag: 'Text',
      x: 440,
      y: 337,
      text: '2017 - 2020',
      fill: '#94A3B8',
      fontSize: 10,
      fontFamily: 'Inter, sans-serif',
      editable: true,
    },
    {
      tag: 'Text',
      x: 290,
      y: 357,
      text: '某互联网公司 · 上海',
      fill: '#94A3B8',
      fontSize: 10,
      fontFamily: 'Inter, sans-serif',
      editable: true,
    },
    {
      tag: 'Text',
      x: 290,
      y: 377,
      width: 280,
      text: '• 负责移动端APP的界面设计和交互优化\n• 参与用户研究，产出可用性报告\n• 与产品和开发团队紧密协作',
      fill: '#475569',
      fontSize: 11,
      fontFamily: 'Inter, sans-serif',
      lineHeight: 20,
      editable: true,
    },
    // 教育背景标题
    {
      tag: 'Text',
      x: 270,
      y: 460,
      text: '教育背景',
      fill: c,
      fontSize: 16,
      fontWeight: '700',
      fontFamily: 'Inter, sans-serif',
      editable: true,
    },
    {
      tag: 'Rect',
      x: 270,
      y: 484,
      width: 40,
      height: 3,
      fill: c,
      cornerRadius: 1.5,
      editable: true,
    },
    {
      tag: 'Text',
      x: 270,
      y: 502,
      text: '视觉传达设计 · 硕士',
      fill: '#1E293B',
      fontSize: 13,
      fontWeight: '600',
      fontFamily: 'Inter, sans-serif',
      editable: true,
    },
    {
      tag: 'Text',
      x: 440,
      y: 502,
      text: '2015 - 2017',
      fill: '#94A3B8',
      fontSize: 10,
      fontFamily: 'Inter, sans-serif',
      editable: true,
    },
    {
      tag: 'Text',
      x: 270,
      y: 522,
      text: '清华大学美术学院',
      fill: '#94A3B8',
      fontSize: 10,
      fontFamily: 'Inter, sans-serif',
      editable: true,
    },
    // 装饰元素（锁定：不可选中/拖动，解锁后可编辑）
    {
      tag: 'Rect',
      id: 'bg-deco',
      x: 240,
      y: 0,
      width: 360,
      height: 6,
      fill: c,
      cornerRadius: 0,
      editable: false,
      hittable: false,
      draggable: false,
    },
  ] as any[];
}
